### PR TITLE
Fix warning when deleting empty folders

### LINKED ISSUE #16: Large number of warnings being raised by `RemoveAssetFromDatabase`
We're frequently getting these warnings from this project.

```
Asset 'Assets/_Game/Content/Chronospheres/ChronosphereUtilities/BiomeEquipmentTables/ClockworkTables/ClockworkItemTables/ClockworkItemTable.asset' that depends on 'Assets/_Game/Content/Clockwork/ClockworkItems/PowerCycle/PowerCycle.asset' doesn't have it as a dependency
UnityEngine.Debug:LogWarning (object)
Ogxd.ProjectCurator.ProjectCurator:RemoveAssetFromDatabase (string) (at ./Library/PackageCache/com.ogxd.project-curator@5a5eb9a295/Editor/ProjectCurator.cs:66)
Ogxd.ProjectCurator.AssetProcessor/<>c__DisplayClass3_0:<OnWillSaveAssets>b__0 () (at ./Library/PackageCache/com.ogxd.project-curator@5a5eb9a295/Editor/AssetProcessor.cs:38)
Ogxd.ProjectCurator.AssetProcessor:OnUpdate () (at ./Library/PackageCache/com.ogxd.project-curator@5a5eb9a295/Editor/AssetProcessor.cs:25)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
```

Is there some actionable fix that should be made here? Otherwise I'd suggest only enabling this warning with a compiler symbol like `PROJECT_CURATOR_DEBUG`, as I'm not sure what we should do about it at our end.

Happy to contribute this change.

### LINKED ISSUE #21: Warning logged when deleting folder
Perhaps only on empty folder

```
ProjectCurator: Asset 'Assets/_Game/Config/Graphs/Statuses' is not present in the database
UnityEngine.Debug:LogWarning (object)
Ogxd.ProjectCurator.ProjectCurator:Warn (string) (at ./Library/PackageCache/com.ogxd.project-curator@6a70b7c196/Editor/ProjectCurator.cs:165)
Ogxd.ProjectCurator.ProjectCurator:RemoveAssetFromDatabase (string) (at ./Library/PackageCache/com.ogxd.project-curator@6a70b7c196/Editor/ProjectCurator.cs:96)
Ogxd.ProjectCurator.AssetProcessor:OnWillDeleteAsset (string,UnityEditor.RemoveAssetOptions) (at ./Library/PackageCache/com.ogxd.project-curator@6a70b7c196/Editor/AssetProcessor.cs:64)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

### PR DESCRIPTION
**Pull request by rhys-vdw**
Closes #21 
Closes #16 

This was caused by a bug in Unity where an incorrect path was being passed to `OnWillCreateAsset`. For folders the path for the meta file was given, instead of the actual folder path. Because the meta file is not an asset, its guid would be zero. When deleting the folder, the correct path is given.

I also did a small tidy on `AssetProcessor`.

Note that I tested this change with @ogxd's refactor branch, and it has no conflicts. (See #22)

### CODE REVIEW

File: Editor/StringUtility.cs [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+      string suffixToRemove,
+      StringComparison comparisonType = StringComparison.CurrentCulture
+    ) {
+      if (suffixToRemove != null && input.EndsWith(suffixToRemove, comparisonType)) {
+        return input[0..^suffixToRemove.Length];
+      }
+      return input;
+    }
+  }
+}
```
Comment (ogxd) [inline Editor/StringUtility.cs]:
```suggestion
using System;

namespace Ogxd.ProjectCurator {
    internal static class StringUtility
    {
        // https://stackoverflow.com/a/7170953/317135
        public static string TrimEnd(
            this string input,
            string suffixToRemove,
            StringComparison comparisonType = StringComparison.CurrentCulture) 
        {
            if (suffixToRemove != null && input.EndsWith(suffixToRemove, comparisonType)) {
                return input[0..^suffixToRemove.Length];
            }
            return input;
        }
    }
}
```

**Comment by ogxd** [comment]
Sorry for the (huge) delay, appart from indentation of StringUtility it looks good to me

**Comment by rhys-vdw** [comment]
> Sorry for the (huge) delay, appart from indentation of StringUtility it looks good to me

I just merged your suggestion without testing.

btw I've been maintaining my own fork due to your inactivity (so all this stuff has been well tested by our team). Happy to move back to yours if you want to add me as a collaborator, also fine with maintaining my own fork. Pretty sure they'll be at parity after this PR is merged. There is still more work to do here, the most egregious outstanding issue is #20. I'm not actively working on this rn, but vaguely plan to come back to it at some stage.
